/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// Body6
    /// </summary>
    [DataContract]
    public partial class Body6 :  IEquatable<Body6>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Body6" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Body6() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Body6" /> class.
        /// </summary>
        /// <param name="name">Name of company (required).</param>
        /// <param name="attributes">Attributes for company creation.</param>
        /// <param name="countryCode">Country code if phone_number is passed in attributes..</param>
        /// <param name="linkedContactsIds">Contact ids to be linked with company.</param>
        /// <param name="linkedDealsIds">Deal ids to be linked with company.</param>
        public Body6(string name = default(string), Object attributes = default(Object), long? countryCode = default(long?), List<long?> linkedContactsIds = default(List<long?>), List<string> linkedDealsIds = default(List<string>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for Body6 and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            this.Attributes = attributes;
            this.CountryCode = countryCode;
            this.LinkedContactsIds = linkedContactsIds;
            this.LinkedDealsIds = linkedDealsIds;
        }
        
        /// <summary>
        /// Name of company
        /// </summary>
        /// <value>Name of company</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Attributes for company creation
        /// </summary>
        /// <value>Attributes for company creation</value>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public Object Attributes { get; set; }

        /// <summary>
        /// Country code if phone_number is passed in attributes.
        /// </summary>
        /// <value>Country code if phone_number is passed in attributes.</value>
        [DataMember(Name="countryCode", EmitDefaultValue=false)]
        public long? CountryCode { get; set; }

        /// <summary>
        /// Contact ids to be linked with company
        /// </summary>
        /// <value>Contact ids to be linked with company</value>
        [DataMember(Name="linkedContactsIds", EmitDefaultValue=false)]
        public List<long?> LinkedContactsIds { get; set; }

        /// <summary>
        /// Deal ids to be linked with company
        /// </summary>
        /// <value>Deal ids to be linked with company</value>
        [DataMember(Name="linkedDealsIds", EmitDefaultValue=false)]
        public List<string> LinkedDealsIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Body6 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  LinkedContactsIds: ").Append(LinkedContactsIds).Append("\n");
            sb.Append("  LinkedDealsIds: ").Append(LinkedDealsIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Body6);
        }

        /// <summary>
        /// Returns true if Body6 instances are equal
        /// </summary>
        /// <param name="input">Instance of Body6 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Body6 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    (this.Attributes != null &&
                    this.Attributes.Equals(input.Attributes))
                ) && 
                (
                    this.CountryCode == input.CountryCode ||
                    (this.CountryCode != null &&
                    this.CountryCode.Equals(input.CountryCode))
                ) && 
                (
                    this.LinkedContactsIds == input.LinkedContactsIds ||
                    this.LinkedContactsIds != null &&
                    this.LinkedContactsIds.SequenceEqual(input.LinkedContactsIds)
                ) && 
                (
                    this.LinkedDealsIds == input.LinkedDealsIds ||
                    this.LinkedDealsIds != null &&
                    this.LinkedDealsIds.SequenceEqual(input.LinkedDealsIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Attributes != null)
                    hashCode = hashCode * 59 + this.Attributes.GetHashCode();
                if (this.CountryCode != null)
                    hashCode = hashCode * 59 + this.CountryCode.GetHashCode();
                if (this.LinkedContactsIds != null)
                    hashCode = hashCode * 59 + this.LinkedContactsIds.GetHashCode();
                if (this.LinkedDealsIds != null)
                    hashCode = hashCode * 59 + this.LinkedDealsIds.GetHashCode();
                return hashCode;
            }
        }
    }

}
