/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// Specify the payment currency and amount. 
    /// </summary>
    [DataContract]
    public partial class Cart :  IEquatable<Cart>
    {
        /// <summary>
        /// Currency code for the payment amount. 
        /// </summary>
        /// <value>Currency code for the payment amount. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CurrencyEnum
        {
            
            /// <summary>
            /// Enum EUR for value: EUR
            /// </summary>
            [EnumMember(Value = "EUR")]
            EUR = 1
        }

        /// <summary>
        /// Currency code for the payment amount. 
        /// </summary>
        /// <value>Currency code for the payment amount. </value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public CurrencyEnum Currency { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Cart" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Cart() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Cart" /> class.
        /// </summary>
        /// <param name="currency">Currency code for the payment amount.  (required).</param>
        /// <param name="specificAmount">Payment amount, in cents.  e.g. if you want to request €12.00, then the amount in cents is 1200.  (required).</param>
        public Cart(CurrencyEnum currency = default(CurrencyEnum), long? specificAmount = default(long?))
        {
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new InvalidDataException("currency is a required property for Cart and cannot be null");
            }
            else
            {
                this.Currency = currency;
            }
            // to ensure "specificAmount" is required (not null)
            if (specificAmount == null)
            {
                throw new InvalidDataException("specificAmount is a required property for Cart and cannot be null");
            }
            else
            {
                this.SpecificAmount = specificAmount;
            }
        }
        

        /// <summary>
        /// Payment amount, in cents.  e.g. if you want to request €12.00, then the amount in cents is 1200. 
        /// </summary>
        /// <value>Payment amount, in cents.  e.g. if you want to request €12.00, then the amount in cents is 1200. </value>
        [DataMember(Name="specificAmount", EmitDefaultValue=false)]
        public long? SpecificAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Cart {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  SpecificAmount: ").Append(SpecificAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Cart);
        }

        /// <summary>
        /// Returns true if Cart instances are equal
        /// </summary>
        /// <param name="input">Instance of Cart to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Cart input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.SpecificAmount == input.SpecificAmount ||
                    (this.SpecificAmount != null &&
                    this.SpecificAmount.Equals(input.SpecificAmount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.SpecificAmount != null)
                    hashCode = hashCode * 59 + this.SpecificAmount.GetHashCode();
                return hashCode;
            }
        }
    }

}
