/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// CreateDomainModel
    /// </summary>
    [DataContract]
    public partial class CreateDomainModel :  IEquatable<CreateDomainModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDomainModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateDomainModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDomainModel" /> class.
        /// </summary>
        /// <param name="id">ID of the Domain created (required).</param>
        /// <param name="domainName">Domain.</param>
        /// <param name="domainProvider">Domain Provider.</param>
        /// <param name="message">Success message.</param>
        /// <param name="dnsRecords">dnsRecords.</param>
        public CreateDomainModel(long? id = default(long?), string domainName = default(string), string domainProvider = default(string), string message = default(string), CreateDomainModelDnsRecords dnsRecords = default(CreateDomainModelDnsRecords))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for CreateDomainModel and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            this.DomainName = domainName;
            this.DomainProvider = domainProvider;
            this.Message = message;
            this.DnsRecords = dnsRecords;
        }
        
        /// <summary>
        /// ID of the Domain created
        /// </summary>
        /// <value>ID of the Domain created</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Domain
        /// </summary>
        /// <value>Domain</value>
        [DataMember(Name="domain_name", EmitDefaultValue=false)]
        public string DomainName { get; set; }

        /// <summary>
        /// Domain Provider
        /// </summary>
        /// <value>Domain Provider</value>
        [DataMember(Name="domain_provider", EmitDefaultValue=false)]
        public string DomainProvider { get; set; }

        /// <summary>
        /// Success message
        /// </summary>
        /// <value>Success message</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets DnsRecords
        /// </summary>
        [DataMember(Name="dns_records", EmitDefaultValue=false)]
        public CreateDomainModelDnsRecords DnsRecords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateDomainModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DomainName: ").Append(DomainName).Append("\n");
            sb.Append("  DomainProvider: ").Append(DomainProvider).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  DnsRecords: ").Append(DnsRecords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateDomainModel);
        }

        /// <summary>
        /// Returns true if CreateDomainModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateDomainModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateDomainModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DomainName == input.DomainName ||
                    (this.DomainName != null &&
                    this.DomainName.Equals(input.DomainName))
                ) && 
                (
                    this.DomainProvider == input.DomainProvider ||
                    (this.DomainProvider != null &&
                    this.DomainProvider.Equals(input.DomainProvider))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.DnsRecords == input.DnsRecords ||
                    (this.DnsRecords != null &&
                    this.DnsRecords.Equals(input.DnsRecords))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.DomainName != null)
                    hashCode = hashCode * 59 + this.DomainName.GetHashCode();
                if (this.DomainProvider != null)
                    hashCode = hashCode * 59 + this.DomainProvider.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.DnsRecords != null)
                    hashCode = hashCode * 59 + this.DnsRecords.GetHashCode();
                return hashCode;
            }
        }
    }

}
