/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// DeleteSubscriptionMemberPayload
    /// </summary>
    [DataContract]
    public partial class DeleteSubscriptionMemberPayload :  IEquatable<DeleteSubscriptionMemberPayload>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteSubscriptionMemberPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeleteSubscriptionMemberPayload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteSubscriptionMemberPayload" /> class.
        /// </summary>
        /// <param name="contactId">Contact Id (required).</param>
        /// <param name="memberContactIds">Member Contact Ids (required).</param>
        public DeleteSubscriptionMemberPayload(int? contactId = default(int?), List<int?> memberContactIds = default(List<int?>))
        {
            // to ensure "contactId" is required (not null)
            if (contactId == null)
            {
                throw new InvalidDataException("contactId is a required property for DeleteSubscriptionMemberPayload and cannot be null");
            }
            else
            {
                this.ContactId = contactId;
            }
            // to ensure "memberContactIds" is required (not null)
            if (memberContactIds == null)
            {
                throw new InvalidDataException("memberContactIds is a required property for DeleteSubscriptionMemberPayload and cannot be null");
            }
            else
            {
                this.MemberContactIds = memberContactIds;
            }
        }
        
        /// <summary>
        /// Contact Id
        /// </summary>
        /// <value>Contact Id</value>
        [DataMember(Name="contactId", EmitDefaultValue=false)]
        public int? ContactId { get; set; }

        /// <summary>
        /// Member Contact Ids
        /// </summary>
        /// <value>Member Contact Ids</value>
        [DataMember(Name="memberContactIds", EmitDefaultValue=false)]
        public List<int?> MemberContactIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeleteSubscriptionMemberPayload {\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  MemberContactIds: ").Append(MemberContactIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeleteSubscriptionMemberPayload);
        }

        /// <summary>
        /// Returns true if DeleteSubscriptionMemberPayload instances are equal
        /// </summary>
        /// <param name="input">Instance of DeleteSubscriptionMemberPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeleteSubscriptionMemberPayload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ContactId == input.ContactId ||
                    (this.ContactId != null &&
                    this.ContactId.Equals(input.ContactId))
                ) && 
                (
                    this.MemberContactIds == input.MemberContactIds ||
                    this.MemberContactIds != null &&
                    this.MemberContactIds.SequenceEqual(input.MemberContactIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContactId != null)
                    hashCode = hashCode * 59 + this.ContactId.GetHashCode();
                if (this.MemberContactIds != null)
                    hashCode = hashCode * 59 + this.MemberContactIds.GetHashCode();
                return hashCode;
            }
        }
    }

}
