/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// GetDomainsListDomains
    /// </summary>
    [DataContract]
    public partial class GetDomainsListDomains :  IEquatable<GetDomainsListDomains>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDomainsListDomains" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetDomainsListDomains() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDomainsListDomains" /> class.
        /// </summary>
        /// <param name="id">Id of the domain (required).</param>
        /// <param name="domainName">Domain name (required).</param>
        /// <param name="authenticated">Status of domain authentication (true&#x3D;authenticated, false&#x3D;non authenticated) (required).</param>
        /// <param name="verified">Status of domain verification (true&#x3D;verified, false&#x3D;non verified) (required).</param>
        /// <param name="ip">Dedicated IP associated with domain.</param>
        public GetDomainsListDomains(long? id = default(long?), string domainName = default(string), bool? authenticated = default(bool?), bool? verified = default(bool?), string ip = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for GetDomainsListDomains and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "domainName" is required (not null)
            if (domainName == null)
            {
                throw new InvalidDataException("domainName is a required property for GetDomainsListDomains and cannot be null");
            }
            else
            {
                this.DomainName = domainName;
            }
            // to ensure "authenticated" is required (not null)
            if (authenticated == null)
            {
                throw new InvalidDataException("authenticated is a required property for GetDomainsListDomains and cannot be null");
            }
            else
            {
                this.Authenticated = authenticated;
            }
            // to ensure "verified" is required (not null)
            if (verified == null)
            {
                throw new InvalidDataException("verified is a required property for GetDomainsListDomains and cannot be null");
            }
            else
            {
                this.Verified = verified;
            }
            this.Ip = ip;
        }
        
        /// <summary>
        /// Id of the domain
        /// </summary>
        /// <value>Id of the domain</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Domain name
        /// </summary>
        /// <value>Domain name</value>
        [DataMember(Name="domain_name", EmitDefaultValue=false)]
        public string DomainName { get; set; }

        /// <summary>
        /// Status of domain authentication (true&#x3D;authenticated, false&#x3D;non authenticated)
        /// </summary>
        /// <value>Status of domain authentication (true&#x3D;authenticated, false&#x3D;non authenticated)</value>
        [DataMember(Name="authenticated", EmitDefaultValue=false)]
        public bool? Authenticated { get; set; }

        /// <summary>
        /// Status of domain verification (true&#x3D;verified, false&#x3D;non verified)
        /// </summary>
        /// <value>Status of domain verification (true&#x3D;verified, false&#x3D;non verified)</value>
        [DataMember(Name="verified", EmitDefaultValue=false)]
        public bool? Verified { get; set; }

        /// <summary>
        /// Dedicated IP associated with domain
        /// </summary>
        /// <value>Dedicated IP associated with domain</value>
        [DataMember(Name="ip", EmitDefaultValue=false)]
        public string Ip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetDomainsListDomains {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DomainName: ").Append(DomainName).Append("\n");
            sb.Append("  Authenticated: ").Append(Authenticated).Append("\n");
            sb.Append("  Verified: ").Append(Verified).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetDomainsListDomains);
        }

        /// <summary>
        /// Returns true if GetDomainsListDomains instances are equal
        /// </summary>
        /// <param name="input">Instance of GetDomainsListDomains to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetDomainsListDomains input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DomainName == input.DomainName ||
                    (this.DomainName != null &&
                    this.DomainName.Equals(input.DomainName))
                ) && 
                (
                    this.Authenticated == input.Authenticated ||
                    (this.Authenticated != null &&
                    this.Authenticated.Equals(input.Authenticated))
                ) && 
                (
                    this.Verified == input.Verified ||
                    (this.Verified != null &&
                    this.Verified.Equals(input.Verified))
                ) && 
                (
                    this.Ip == input.Ip ||
                    (this.Ip != null &&
                    this.Ip.Equals(input.Ip))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.DomainName != null)
                    hashCode = hashCode * 59 + this.DomainName.GetHashCode();
                if (this.Authenticated != null)
                    hashCode = hashCode * 59 + this.Authenticated.GetHashCode();
                if (this.Verified != null)
                    hashCode = hashCode * 59 + this.Verified.GetHashCode();
                if (this.Ip != null)
                    hashCode = hashCode * 59 + this.Ip.GetHashCode();
                return hashCode;
            }
        }
    }

}
