/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// GetSubscriptionInfoResponse
    /// </summary>
    [DataContract]
    public partial class GetSubscriptionInfoResponse :  IEquatable<GetSubscriptionInfoResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSubscriptionInfoResponse" /> class.
        /// </summary>
        /// <param name="balance">balance.</param>
        /// <param name="tier">Tier Information.</param>
        /// <param name="members">Subscription Member Information.</param>
        public GetSubscriptionInfoResponse(GetSubscriptionInfoResponseBalance balance = default(GetSubscriptionInfoResponseBalance), List<GetSubscriptionInfoResponseTier> tier = default(List<GetSubscriptionInfoResponseTier>), List<GetSubscriptionInfoResponseMembers> members = default(List<GetSubscriptionInfoResponseMembers>))
        {
            this.Balance = balance;
            this.Tier = tier;
            this.Members = members;
        }
        
        /// <summary>
        /// Gets or Sets Balance
        /// </summary>
        [DataMember(Name="balance", EmitDefaultValue=false)]
        public GetSubscriptionInfoResponseBalance Balance { get; set; }

        /// <summary>
        /// Tier Information
        /// </summary>
        /// <value>Tier Information</value>
        [DataMember(Name="tier", EmitDefaultValue=false)]
        public List<GetSubscriptionInfoResponseTier> Tier { get; set; }

        /// <summary>
        /// Subscription Member Information
        /// </summary>
        /// <value>Subscription Member Information</value>
        [DataMember(Name="members", EmitDefaultValue=false)]
        public List<GetSubscriptionInfoResponseMembers> Members { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetSubscriptionInfoResponse {\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetSubscriptionInfoResponse);
        }

        /// <summary>
        /// Returns true if GetSubscriptionInfoResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetSubscriptionInfoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSubscriptionInfoResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Balance == input.Balance ||
                    (this.Balance != null &&
                    this.Balance.Equals(input.Balance))
                ) && 
                (
                    this.Tier == input.Tier ||
                    this.Tier != null &&
                    this.Tier.SequenceEqual(input.Tier)
                ) && 
                (
                    this.Members == input.Members ||
                    this.Members != null &&
                    this.Members.SequenceEqual(input.Members)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Balance != null)
                    hashCode = hashCode * 59 + this.Balance.GetHashCode();
                if (this.Tier != null)
                    hashCode = hashCode * 59 + this.Tier.GetHashCode();
                if (this.Members != null)
                    hashCode = hashCode * 59 + this.Members.GetHashCode();
                return hashCode;
            }
        }
    }

}
