/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// InviteAdminUser
    /// </summary>
    [DataContract]
    public partial class InviteAdminUser :  IEquatable<InviteAdminUser>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InviteAdminUser" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InviteAdminUser() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InviteAdminUser" /> class.
        /// </summary>
        /// <param name="email">Email address for the organization (required).</param>
        /// <param name="allFeaturesAccess">All access to the features (required).</param>
        /// <param name="groupIds">Ids of Group.</param>
        /// <param name="privileges">privileges (required).</param>
        public InviteAdminUser(string email = default(string), bool? allFeaturesAccess = default(bool?), List<string> groupIds = default(List<string>), List<InviteAdminUserPrivileges> privileges = default(List<InviteAdminUserPrivileges>))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for InviteAdminUser and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "allFeaturesAccess" is required (not null)
            if (allFeaturesAccess == null)
            {
                throw new InvalidDataException("allFeaturesAccess is a required property for InviteAdminUser and cannot be null");
            }
            else
            {
                this.AllFeaturesAccess = allFeaturesAccess;
            }
            // to ensure "privileges" is required (not null)
            if (privileges == null)
            {
                throw new InvalidDataException("privileges is a required property for InviteAdminUser and cannot be null");
            }
            else
            {
                this.Privileges = privileges;
            }
            this.GroupIds = groupIds;
        }
        
        /// <summary>
        /// Email address for the organization
        /// </summary>
        /// <value>Email address for the organization</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// All access to the features
        /// </summary>
        /// <value>All access to the features</value>
        [DataMember(Name="all_features_access", EmitDefaultValue=false)]
        public bool? AllFeaturesAccess { get; set; }

        /// <summary>
        /// Ids of Group
        /// </summary>
        /// <value>Ids of Group</value>
        [DataMember(Name="groupIds", EmitDefaultValue=false)]
        public List<string> GroupIds { get; set; }

        /// <summary>
        /// Gets or Sets Privileges
        /// </summary>
        [DataMember(Name="privileges", EmitDefaultValue=false)]
        public List<InviteAdminUserPrivileges> Privileges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InviteAdminUser {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  AllFeaturesAccess: ").Append(AllFeaturesAccess).Append("\n");
            sb.Append("  GroupIds: ").Append(GroupIds).Append("\n");
            sb.Append("  Privileges: ").Append(Privileges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InviteAdminUser);
        }

        /// <summary>
        /// Returns true if InviteAdminUser instances are equal
        /// </summary>
        /// <param name="input">Instance of InviteAdminUser to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InviteAdminUser input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.AllFeaturesAccess == input.AllFeaturesAccess ||
                    (this.AllFeaturesAccess != null &&
                    this.AllFeaturesAccess.Equals(input.AllFeaturesAccess))
                ) && 
                (
                    this.GroupIds == input.GroupIds ||
                    this.GroupIds != null &&
                    this.GroupIds.SequenceEqual(input.GroupIds)
                ) && 
                (
                    this.Privileges == input.Privileges ||
                    this.Privileges != null &&
                    this.Privileges.SequenceEqual(input.Privileges)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.AllFeaturesAccess != null)
                    hashCode = hashCode * 59 + this.AllFeaturesAccess.GetHashCode();
                if (this.GroupIds != null)
                    hashCode = hashCode * 59 + this.GroupIds.GetHashCode();
                if (this.Privileges != null)
                    hashCode = hashCode * 59 + this.Privileges.GetHashCode();
                return hashCode;
            }
        }
    }

}
