/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// Details of the plan to be changed
    /// </summary>
    [DataContract]
    public partial class SubAccountsUpdatePlanRequest :  IEquatable<SubAccountsUpdatePlanRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubAccountsUpdatePlanRequest" /> class.
        /// </summary>
        /// <param name="subAccountIds">List of sub-account ids.</param>
        /// <param name="credits">credits.</param>
        /// <param name="features">features.</param>
        public SubAccountsUpdatePlanRequest(List<long?> subAccountIds = default(List<long?>), SubAccountsUpdatePlanRequestCredits credits = default(SubAccountsUpdatePlanRequestCredits), SubAccountsUpdatePlanRequestFeatures features = default(SubAccountsUpdatePlanRequestFeatures))
        {
            this.SubAccountIds = subAccountIds;
            this.Credits = credits;
            this.Features = features;
        }
        
        /// <summary>
        /// List of sub-account ids
        /// </summary>
        /// <value>List of sub-account ids</value>
        [DataMember(Name="subAccountIds", EmitDefaultValue=false)]
        public List<long?> SubAccountIds { get; set; }

        /// <summary>
        /// Gets or Sets Credits
        /// </summary>
        [DataMember(Name="credits", EmitDefaultValue=false)]
        public SubAccountsUpdatePlanRequestCredits Credits { get; set; }

        /// <summary>
        /// Gets or Sets Features
        /// </summary>
        [DataMember(Name="features", EmitDefaultValue=false)]
        public SubAccountsUpdatePlanRequestFeatures Features { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubAccountsUpdatePlanRequest {\n");
            sb.Append("  SubAccountIds: ").Append(SubAccountIds).Append("\n");
            sb.Append("  Credits: ").Append(Credits).Append("\n");
            sb.Append("  Features: ").Append(Features).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubAccountsUpdatePlanRequest);
        }

        /// <summary>
        /// Returns true if SubAccountsUpdatePlanRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SubAccountsUpdatePlanRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubAccountsUpdatePlanRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SubAccountIds == input.SubAccountIds ||
                    this.SubAccountIds != null &&
                    this.SubAccountIds.SequenceEqual(input.SubAccountIds)
                ) && 
                (
                    this.Credits == input.Credits ||
                    (this.Credits != null &&
                    this.Credits.Equals(input.Credits))
                ) && 
                (
                    this.Features == input.Features ||
                    (this.Features != null &&
                    this.Features.Equals(input.Features))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubAccountIds != null)
                    hashCode = hashCode * 59 + this.SubAccountIds.GetHashCode();
                if (this.Credits != null)
                    hashCode = hashCode * 59 + this.Credits.GetHashCode();
                if (this.Features != null)
                    hashCode = hashCode * 59 + this.Features.GetHashCode();
                return hashCode;
            }
        }
    }

}
