/* 
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = brevo_csharp.Client.SwaggerDateConverter;

namespace brevo_csharp.Model
{
    /// <summary>
    /// Response containing transaction history details for a specific balance and contact.
    /// </summary>
    [DataContract]
    public partial class TransactionHistoryResp :  IEquatable<TransactionHistoryResp>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionHistoryResp" /> class.
        /// </summary>
        /// <param name="balanceDefinitionId">Unique identifier of the associated balance definition..</param>
        /// <param name="contactId">Unique identifier of the contact related to the transactions..</param>
        /// <param name="count">Total number of transactions in the history..</param>
        /// <param name="loyaltyProgramId">Unique identifier of the associated loyalty program..</param>
        /// <param name="transactionHistory">List of past transactions associated with the balance..</param>
        public TransactionHistoryResp(string balanceDefinitionId = default(string), int? contactId = default(int?), int? count = default(int?), string loyaltyProgramId = default(string), List<TransactionHistory> transactionHistory = default(List<TransactionHistory>))
        {
            this.BalanceDefinitionId = balanceDefinitionId;
            this.ContactId = contactId;
            this.Count = count;
            this.LoyaltyProgramId = loyaltyProgramId;
            this.TransactionHistory = transactionHistory;
        }
        
        /// <summary>
        /// Unique identifier of the associated balance definition.
        /// </summary>
        /// <value>Unique identifier of the associated balance definition.</value>
        [DataMember(Name="balanceDefinitionId", EmitDefaultValue=false)]
        public string BalanceDefinitionId { get; set; }

        /// <summary>
        /// Unique identifier of the contact related to the transactions.
        /// </summary>
        /// <value>Unique identifier of the contact related to the transactions.</value>
        [DataMember(Name="contactId", EmitDefaultValue=false)]
        public int? ContactId { get; set; }

        /// <summary>
        /// Total number of transactions in the history.
        /// </summary>
        /// <value>Total number of transactions in the history.</value>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public int? Count { get; set; }

        /// <summary>
        /// Unique identifier of the associated loyalty program.
        /// </summary>
        /// <value>Unique identifier of the associated loyalty program.</value>
        [DataMember(Name="loyaltyProgramId", EmitDefaultValue=false)]
        public string LoyaltyProgramId { get; set; }

        /// <summary>
        /// List of past transactions associated with the balance.
        /// </summary>
        /// <value>List of past transactions associated with the balance.</value>
        [DataMember(Name="transactionHistory", EmitDefaultValue=false)]
        public List<TransactionHistory> TransactionHistory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionHistoryResp {\n");
            sb.Append("  BalanceDefinitionId: ").Append(BalanceDefinitionId).Append("\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  LoyaltyProgramId: ").Append(LoyaltyProgramId).Append("\n");
            sb.Append("  TransactionHistory: ").Append(TransactionHistory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionHistoryResp);
        }

        /// <summary>
        /// Returns true if TransactionHistoryResp instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionHistoryResp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionHistoryResp input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BalanceDefinitionId == input.BalanceDefinitionId ||
                    (this.BalanceDefinitionId != null &&
                    this.BalanceDefinitionId.Equals(input.BalanceDefinitionId))
                ) && 
                (
                    this.ContactId == input.ContactId ||
                    (this.ContactId != null &&
                    this.ContactId.Equals(input.ContactId))
                ) && 
                (
                    this.Count == input.Count ||
                    (this.Count != null &&
                    this.Count.Equals(input.Count))
                ) && 
                (
                    this.LoyaltyProgramId == input.LoyaltyProgramId ||
                    (this.LoyaltyProgramId != null &&
                    this.LoyaltyProgramId.Equals(input.LoyaltyProgramId))
                ) && 
                (
                    this.TransactionHistory == input.TransactionHistory ||
                    this.TransactionHistory != null &&
                    this.TransactionHistory.SequenceEqual(input.TransactionHistory)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BalanceDefinitionId != null)
                    hashCode = hashCode * 59 + this.BalanceDefinitionId.GetHashCode();
                if (this.ContactId != null)
                    hashCode = hashCode * 59 + this.ContactId.GetHashCode();
                if (this.Count != null)
                    hashCode = hashCode * 59 + this.Count.GetHashCode();
                if (this.LoyaltyProgramId != null)
                    hashCode = hashCode * 59 + this.LoyaltyProgramId.GetHashCode();
                if (this.TransactionHistory != null)
                    hashCode = hashCode * 59 + this.TransactionHistory.GetHashCode();
                return hashCode;
            }
        }
    }

}
